# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
ignore: |
  vendor/*
  test/vendor/*
  internal/northbound/testdata/bloggen-sample/*
  deployments/postgres/templates/postgres-secrets.yaml
  deployments/postgres/templates/pvc.yaml
  deployments/postgres/templates/service.yaml
  deployments/postgres/templates/deployment.yaml
  deployments/application-catalog/templates/tests/test-connection.yaml
  deployments/application-catalog/templates/configmap.yaml
  deployments/application-catalog/templates/postgres-secrets.yaml
  deployments/application-catalog/templates/service.yaml
  deployments/application-catalog/templates/ingress.yaml
  deployments/application-catalog/templates/deployment.yaml
  internal/northbound/testdata/*
  test/catalog-*-test.yaml
  .github/
rules:
  line-length:
    level: warning
    ignore: |
      api/spec/*.yaml
      deployments/keycloak-dev/values.yaml
      deployments/application-catalog/values.yaml
      pkg/schema/generator/catalog-schema-base.yaml
      pkg/schema/catalog-schema.yaml
      internal/northbound/testdata/*
  document-start:
    level: warning
    ignore: |
      api/spec/openapi.yaml
  comments:
    level: error
  comments-indentation:
    level: error
  truthy:
    level: error
  empty-values: enable
