# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
ignore: |
  test/catalog-*-test.yaml
  .cache
  vendor
  ci
  .github/workflows
  pkg/schema
  api/spec/openapi.yaml
  internal/northbound/testdata
  deployments/app-orch-catalog/templates
  app-orch-tutorials/developer-guide-tutorial/tutorial-web-ui/node_modules/
  venv
  .github/
extends: default
rules:
  line-length:
    level: warning
    max: 200
    ignore: |
      api/spec/*.yaml
      deployments/keycloak-dev/values.yaml
      deployments/application-catalog/values.yaml
      pkg/schema/generator/catalog-schema-base.yaml
      pkg/schema/catalog-schema.yaml
      internal/northbound/testdata/*
  document-start:
    level: warning
    ignore: |
      api/spec/openapi.yaml
  comments:
    level: error
  comments-indentation:
    level: error
  truthy:
    level: error
  empty-values: enable
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 5
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 5
  colons:
    max-spaces-before: 1
    max-spaces-after: 5
