// SPDX-FileCopyrightText: 2023-present Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

package exporter

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	b64 "encoding/base64"
	"fmt"

	catalogv3 "github.com/open-edge-platform/app-orch-catalog/pkg/api/catalog/v3"
	"github.com/open-edge-platform/app-orch-catalog/pkg/schema/upload"
	"gopkg.in/yaml.v3"
)

const (
	schemaVersion = "0.1"
)

// Exporter implements the functions used to export YAML files
type Exporter struct {
	output    []string
	TarBuffer *bytes.Buffer
	TarWriter *tar.Writer
}

// LogChange prints the given formatted output to stdout if the verbose flag is enabled
func (e *Exporter) LogChange(format string, a ...any) {
	e.output = append(e.output, fmt.Sprintf(format, a...))
}

// GetOutput returns the output generated by the command
func (e *Exporter) GetOutput() []string {
	return e.output
}

// NewExporter returns an initialized loader
func NewExporter() *Exporter {
	return &Exporter{
		output: make([]string, 0),
	}
}

func appendHeader(yaml []byte) []byte {
	header := "---\n"
	return append([]byte(header), yaml...)
}

func specToBytes(spec *upload.YamlSpec) ([]byte, error) {
	// Marshal the spec into YAML and write the file
	data, err := yaml.Marshal(spec)
	if err != nil {
		return nil, err
	}
	data = appendHeader(data)
	return data, nil
}

func (e *Exporter) ExportRegistry(reg *catalogv3.Registry) ([]byte, error) {
	spec := &upload.YamlSpec{
		SpecSchema:    upload.RegistryType,
		SchemaVersion: schemaVersion,
		Name:          reg.Name,
		DisplayName:   reg.DisplayName,
		Description:   reg.Description,
		RootURL:       reg.RootUrl,
		UserName:      reg.Username,
		AuthToken:     reg.AuthToken,
		CACerts:       reg.Cacerts,
		Type:          reg.Type,
	}

	return specToBytes(spec)
}

func (e *Exporter) ExportArtifact(art *catalogv3.Artifact) ([]byte, error) {
	e.LogChange("Exporting artifact %s\n", art.Name)
	spec := &upload.YamlSpec{
		SpecSchema:    upload.ArtifactType,
		SchemaVersion: schemaVersion,
		Name:          art.Name,
		DisplayName:   art.DisplayName,
		Description:   art.Description,
		MimeType:      art.MimeType,
		Artifact:      b64.StdEncoding.EncodeToString(art.Artifact),
	}

	return specToBytes(spec)
}

func (e *Exporter) ExportApplication(app *catalogv3.Application) ([]byte, map[string][]byte, error) {
	e.LogChange("Exporting application %s\n", app.Name)
	profiles, profileData, err := e.exportProfiles(app)
	ignoredResources := e.exportIgnoredResources(app)
	if err != nil {
		return nil, nil, err
	}
	spec := &upload.YamlSpec{
		SpecSchema:       upload.ApplicationType,
		SchemaVersion:    schemaVersion,
		Name:             app.Name,
		Version:          app.Version,
		DisplayName:      app.DisplayName,
		Description:      app.Description,
		HelmRegistry:     app.HelmRegistryName,
		ImageRegistry:    app.ImageRegistryName,
		ChartName:        app.ChartName,
		ChartVersion:     app.ChartVersion,
		Profiles:         profiles,
		DefaultProfile:   app.DefaultProfileName,
		IgnoredResources: ignoredResources,
	}

	data, err := specToBytes(spec)
	if err != nil {
		return nil, nil, err
	}

	return data, profileData, err
}

func (e *Exporter) exportProfiles(app *catalogv3.Application) ([]upload.Profile, map[string][]byte, error) {
	profiles := make([]upload.Profile, 0, len(app.Profiles))
	profileData := map[string][]byte{}
	for _, p := range app.Profiles {
		fileName, thisProfileData, err := e.exportProfile(app, p)
		if err != nil {
			return nil, nil, err
		}
		profileData[fileName] = thisProfileData
		spec := upload.Profile{
			Name:                   p.Name,
			DisplayName:            p.DisplayName,
			Description:            p.Description,
			ValuesFileName:         fileName,
			DeploymentRequirements: e.exportDeploymentRequirements(p),
			ParameterTemplates:     e.exportParameterTemplates(p),
		}

		profiles = append(profiles, spec)
	}
	return profiles, profileData, nil
}

func (e *Exporter) exportProfile(app *catalogv3.Application, p *catalogv3.Profile) (string, []byte, error) {
	e.LogChange("Exporting profile %s\n", p.Name)
	baseFile := fmt.Sprintf("values-%s-%s-%s.yaml", app.Name, app.Version, p.Name)
	return baseFile, []byte(p.ChartValues), nil
}

func (e *Exporter) exportIgnoredResources(app *catalogv3.Application) []upload.ResourceReference {
	if app.IgnoredResources == nil {
		return []upload.ResourceReference{}
	}
	resources := make([]upload.ResourceReference, 0, len(app.IgnoredResources))
	for _, r := range app.IgnoredResources {
		resources = append(resources, upload.ResourceReference{Name: r.Name, Kind: r.Kind, Namespace: r.Namespace})
	}
	return resources
}

func (e *Exporter) exportDeploymentRequirements(p *catalogv3.Profile) []upload.DeploymentRequirement {
	requirements := make([]upload.DeploymentRequirement, 0, len(p.DeploymentRequirement))
	for _, dr := range p.DeploymentRequirement {
		requirements = append(requirements, upload.DeploymentRequirement{
			Name:              dr.Name,
			Version:           dr.Version,
			DeploymentProfile: dr.DeploymentProfileName,
		})
	}
	return requirements
}

func (e *Exporter) exportParameterTemplates(p *catalogv3.Profile) []upload.ParameterTemplate {
	templates := make([]upload.ParameterTemplate, 0, len(p.ParameterTemplates))
	for _, pt := range p.ParameterTemplates {
		templates = append(templates, upload.ParameterTemplate{
			Name:            pt.Name,
			DisplayName:     pt.DisplayName,
			Type:            pt.Type,
			Default:         pt.Default,
			Validator:       pt.Validator,
			SuggestedValues: pt.SuggestedValues,
			Secret:          pt.Secret,
			Mandatory:       pt.Mandatory,
		})
	}
	return templates
}

func (e *Exporter) exportExtensions(exts []*catalogv3.APIExtension) []upload.APIExtension {
	extensions := make([]upload.APIExtension, 0, len(exts))
	for _, ext := range exts {
		extensions = append(extensions, e.exportExtension(ext))
	}
	return extensions
}

func (e *Exporter) exportExtension(ext *catalogv3.APIExtension) upload.APIExtension {
	extension := upload.APIExtension{
		Name:        ext.Name,
		Version:     ext.Version,
		DisplayName: ext.DisplayName,
		Description: ext.Description,
		Endpoints:   nil,
	}

	if ext.UiExtension != nil {
		extension.UIExtension = &upload.UIExtension{
			Label:       &ext.UiExtension.Label,
			ServiceName: ext.UiExtension.ServiceName,
			Description: ext.UiExtension.Description,
			FileName:    ext.UiExtension.FileName,
			AppName:     ext.UiExtension.AppName,
			ModuleName:  ext.UiExtension.ModuleName,
		}
	}

	if ext.Endpoints != nil {
		extension.Endpoints = make([]*upload.Endpoint, 0, len(ext.Endpoints))
		for _, ep := range ext.Endpoints {
			extension.Endpoints = append(extension.Endpoints, &upload.Endpoint{
				ServiceName:  ep.ServiceName,
				ExternalPath: ep.ExternalPath,
				InternalPath: ep.InternalPath,
				Scheme:       ep.Scheme,
				AuthType:     ep.AuthType,
				AppName:      ep.AppName,
			})
		}
	}

	return extension
}

func (e *Exporter) ExportDeploymentPackage(pkg *catalogv3.DeploymentPackage) ([]byte, error) {

	e.LogChange("Exporting deployment package %s\n", pkg.Name)
	spec := &upload.YamlSpec{
		SpecSchema:                 upload.DeploymentPackageType,
		SchemaVersion:              schemaVersion,
		Name:                       pkg.Name,
		Version:                    pkg.Version,
		DisplayName:                pkg.DisplayName,
		Description:                pkg.Description,
		Applications:               e.exportApplicationReferences(pkg),
		ApplicationDependencies:    e.exportApplicationDependencies(pkg),
		DeploymentProfiles:         e.exportDeploymentProfiles(pkg),
		DefaultProfile:             pkg.DefaultProfileName,
		IsDeployed:                 pkg.IsDeployed,
		IsVisible:                  pkg.IsVisible,
		ForbidsMultipleDeployments: pkg.ForbidsMultipleDeployments,
		Extensions:                 e.exportExtensions(pkg.Extensions),
		DefaultNamespaces:          e.exportDefaultNamespaces(pkg.DefaultNamespaces),
		Namespaces:                 e.exportNamespaces(pkg.Namespaces),
	}
	return specToBytes(spec)
}

func (e *Exporter) exportDeploymentProfiles(app *catalogv3.DeploymentPackage) []upload.DeploymentProfile {
	profiles := make([]upload.DeploymentProfile, 0, len(app.Profiles))
	for _, p := range app.Profiles {
		appProfiles := make([]upload.ApplicationProfile, 0, len(app.Profiles))
		for appName, profileName := range p.ApplicationProfiles {
			appProfiles = append(appProfiles, upload.ApplicationProfile{ApplicationName: appName, ProfileName: profileName})
		}
		profiles = append(profiles, upload.DeploymentProfile{
			Name:                p.Name,
			DisplayName:         p.DisplayName,
			Description:         p.Description,
			ApplicationProfiles: appProfiles,
		})
	}
	return profiles
}

func (e *Exporter) exportApplicationReferences(pkg *catalogv3.DeploymentPackage) []upload.Application {
	apprefs := make([]upload.Application, 0, len(pkg.ApplicationReferences))
	for _, ref := range pkg.ApplicationReferences {
		apprefs = append(apprefs, upload.Application{
			Name:    ref.Name,
			Version: ref.Version,
		})
	}
	return apprefs
}

func (e *Exporter) exportApplicationDependencies(pkg *catalogv3.DeploymentPackage) []upload.ApplicationDependency {
	appdeps := make([]upload.ApplicationDependency, 0, len(pkg.ApplicationDependencies))
	for _, dep := range pkg.ApplicationDependencies {
		appdeps = append(appdeps, upload.ApplicationDependency{
			Name:     dep.Name,
			Requires: dep.Requires,
		})
	}
	return appdeps
}

func (e *Exporter) exportDefaultNamespaces(namespaces map[string]string) map[string]string {
	return namespaces
}

func (e *Exporter) exportNamespaces(namespaces []*catalogv3.Namespace) []upload.Namespace {
	list := make([]upload.Namespace, 0)
	for _, ns := range namespaces {
		item := upload.Namespace{Name: ns.Name}
		item.Labels = ns.Labels
		item.Annotations = ns.Annotations
		list = append(list, item)
	}
	return list
}

func (e *Exporter) NewTarball() {
	e.TarBuffer = &bytes.Buffer{}
	e.TarWriter = tar.NewWriter(e.TarBuffer)
}

func (e *Exporter) AddToTarball(filename string, data []byte) error {
	if e.TarWriter == nil {
		return fmt.Errorf("tar writer is not initialized")
	}
	hdr := &tar.Header{
		Name: filename,
		Mode: 0600,
		Size: int64(len(data)),
	}
	if err := e.TarWriter.WriteHeader(hdr); err != nil {
		return fmt.Errorf("error writing tar header for %s: %w", filename, err)
	}
	if _, err := e.TarWriter.Write(data); err != nil {
		return fmt.Errorf("error writing data to tar for %s: %w", filename, err)
	}
	return nil
}

func (e *Exporter) CloseTarball() ([]byte, error) {
	if e.TarWriter == nil {
		return nil, fmt.Errorf("tar writer is not initialized")
	}
	if err := e.TarWriter.Close(); err != nil {
		return nil, fmt.Errorf("error closing tar writer: %w", err)
	}
	data := e.TarBuffer.Bytes()

	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	_, err := gz.Write(data)
	if err != nil {
		return nil, fmt.Errorf("error compressing tarball: %w", err)
	}
	if err := gz.Close(); err != nil {
		return nil, fmt.Errorf("error closing gzip writer: %w", err)
	}

	e.TarWriter = nil
	e.TarBuffer = nil

	return buf.Bytes(), nil
}
