-- Create "applications" table
CREATE TABLE "applications" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "version" character varying NOT NULL, "chart_name" character varying NOT NULL, "chart_version" character varying NOT NULL, "application_default_profile" bigint NULL, "publisher_applications" bigint NOT NULL, "registry_applications" bigint NOT NULL, "registry_application_images" bigint NULL, PRIMARY KEY ("id"));
-- Create index "application_name_version_publisher_applications" to table: "applications"
CREATE UNIQUE INDEX "application_name_version_publisher_applications" ON "applications" ("name", "version", "publisher_applications");
-- Create "application_dependencies" table
CREATE TABLE "application_dependencies" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "application_dependency_source_fk" bigint NOT NULL, "application_dependency_target_fk" bigint NOT NULL, "deployment_package_application_dependencies" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "application_namespaces" table
CREATE TABLE "application_namespaces" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "namespace" character varying NOT NULL, "application_namespace_source_fk" bigint NOT NULL, "deployment_package_application_namespaces" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "artifacts" table
CREATE TABLE "artifacts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "mime_type" character varying NOT NULL, "artifact" bytea NOT NULL, "publisher_artifacts" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "artifact_name_publisher_artifacts" to table: "artifacts"
CREATE UNIQUE INDEX "artifact_name_publisher_artifacts" ON "artifacts" ("name", "publisher_artifacts");
-- Create "artifact_references" table
CREATE TABLE "artifact_references" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "purpose" character varying NOT NULL, "artifact_reference_artifact" bigint NOT NULL, "deployment_package_artifacts" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create "common_mixins" table
CREATE TABLE "common_mixins" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "deployment_packages" table
CREATE TABLE "deployment_packages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "version" character varying NOT NULL, "is_deployed" boolean NULL, "is_visible" boolean NULL, "deployment_package_default_profile" bigint NULL, "publisher_deployment_packages" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "deploymentpackage_name_version_publisher_deployment_packages" to table: "deployment_packages"
CREATE UNIQUE INDEX "deploymentpackage_name_version_publisher_deployment_packages" ON "deployment_packages" ("name", "version", "publisher_deployment_packages");
-- Create "deployment_profiles" table
CREATE TABLE "deployment_profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "deployment_package_deployment_profiles" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "deploymentprofile_name_deployment_package_deployment_profiles" to table: "deployment_profiles"
CREATE UNIQUE INDEX "deploymentprofile_name_deployment_package_deployment_profiles" ON "deployment_profiles" ("name", "deployment_package_deployment_profiles");
-- Create "endpoints" table
CREATE TABLE "endpoints" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "service_name" character varying NOT NULL, "external_path" character varying NOT NULL, "internal_path" character varying NOT NULL, "scheme" character varying NOT NULL, "auth_type" character varying NOT NULL, "extension_endpoints" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "endpoint_service_name_extension_endpoints" to table: "endpoints"
CREATE UNIQUE INDEX "endpoint_service_name_extension_endpoints" ON "endpoints" ("service_name", "extension_endpoints");
-- Create "extensions" table
CREATE TABLE "extensions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "version" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "ui_label" character varying NULL, "ui_service_name" character varying NULL, "deployment_package_extensions" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "extension_name_version_deployment_package_extensions" to table: "extensions"
CREATE UNIQUE INDEX "extension_name_version_deployment_package_extensions" ON "extensions" ("name", "version", "deployment_package_extensions");
-- Create "profiles" table
CREATE TABLE "profiles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "chart_values" character varying NOT NULL, "application_profiles" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "profile_name_application_profiles" to table: "profiles"
CREATE UNIQUE INDEX "profile_name_application_profiles" ON "profiles" ("name", "application_profiles");
-- Create "publishers" table
CREATE TABLE "publishers" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "publisher_name" to table: "publishers"
CREATE UNIQUE INDEX "publisher_name" ON "publishers" ("name");
-- Create "registries" table
CREATE TABLE "registries" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "description" character varying NULL, "create_time" timestamptz NOT NULL, "update_time" timestamptz NOT NULL, "root_url" character varying NULL, "username" character varying NULL, "auth_token" character varying NULL, "cacerts" character varying NULL, "type" character varying NOT NULL, "publisher_registries" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "registry_name_publisher_registries" to table: "registries"
CREATE UNIQUE INDEX "registry_name_publisher_registries" ON "registries" ("name", "publisher_registries");
-- Create "deployment_package_applications" table
CREATE TABLE "deployment_package_applications" ("deployment_package_id" bigint NOT NULL, "application_id" bigint NOT NULL, PRIMARY KEY ("deployment_package_id", "application_id"));
-- Create "deployment_package_icon" table
CREATE TABLE "deployment_package_icon" ("deployment_package_id" bigint NOT NULL, "artifact_id" bigint NOT NULL, PRIMARY KEY ("deployment_package_id", "artifact_id"));
-- Create "deployment_package_thumbnail" table
CREATE TABLE "deployment_package_thumbnail" ("deployment_package_id" bigint NOT NULL, "artifact_id" bigint NOT NULL, PRIMARY KEY ("deployment_package_id", "artifact_id"));
-- Create "deployment_profile_profiles" table
CREATE TABLE "deployment_profile_profiles" ("deployment_profile_id" bigint NOT NULL, "profile_id" bigint NOT NULL, PRIMARY KEY ("deployment_profile_id", "profile_id"));
-- Modify "applications" table
ALTER TABLE "applications" ADD CONSTRAINT "applications_profiles_default_profile" FOREIGN KEY ("application_default_profile") REFERENCES "profiles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "applications_publishers_applications" FOREIGN KEY ("publisher_applications") REFERENCES "publishers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "applications_registries_application_images" FOREIGN KEY ("registry_application_images") REFERENCES "registries" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "applications_registries_applications" FOREIGN KEY ("registry_applications") REFERENCES "registries" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "application_dependencies" table
ALTER TABLE "application_dependencies" ADD CONSTRAINT "application_dependencies_applications_source_fk" FOREIGN KEY ("application_dependency_source_fk") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "application_dependencies_applications_target_fk" FOREIGN KEY ("application_dependency_target_fk") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "application_dependencies_deplo_7859c568897dabcc699de5dc7dcfaa63" FOREIGN KEY ("deployment_package_application_dependencies") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "application_namespaces" table
ALTER TABLE "application_namespaces" ADD CONSTRAINT "application_namespaces_applications_source_fk" FOREIGN KEY ("application_namespace_source_fk") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "application_namespaces_deploym_5a743904270476da336a2a0ac82ba874" FOREIGN KEY ("deployment_package_application_namespaces") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "artifacts" table
ALTER TABLE "artifacts" ADD CONSTRAINT "artifacts_publishers_artifacts" FOREIGN KEY ("publisher_artifacts") REFERENCES "publishers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "artifact_references" table
ALTER TABLE "artifact_references" ADD CONSTRAINT "artifact_references_artifacts_artifact" FOREIGN KEY ("artifact_reference_artifact") REFERENCES "artifacts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "artifact_references_deployment_packages_artifacts" FOREIGN KEY ("deployment_package_artifacts") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_packages" table
ALTER TABLE "deployment_packages" ADD CONSTRAINT "deployment_packages_deployment_profiles_default_profile" FOREIGN KEY ("deployment_package_default_profile") REFERENCES "deployment_profiles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, ADD CONSTRAINT "deployment_packages_publishers_deployment_packages" FOREIGN KEY ("publisher_deployment_packages") REFERENCES "publishers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_profiles" table
ALTER TABLE "deployment_profiles" ADD CONSTRAINT "deployment_profiles_deployment_packages_deployment_profiles" FOREIGN KEY ("deployment_package_deployment_profiles") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "endpoints" table
ALTER TABLE "endpoints" ADD CONSTRAINT "endpoints_extensions_endpoints" FOREIGN KEY ("extension_endpoints") REFERENCES "extensions" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "extensions" table
ALTER TABLE "extensions" ADD CONSTRAINT "extensions_deployment_packages_extensions" FOREIGN KEY ("deployment_package_extensions") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "profiles" table
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_applications_profiles" FOREIGN KEY ("application_profiles") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "registries" table
ALTER TABLE "registries" ADD CONSTRAINT "registries_publishers_registries" FOREIGN KEY ("publisher_registries") REFERENCES "publishers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_package_applications" table
ALTER TABLE "deployment_package_applications" ADD CONSTRAINT "deployment_package_applications_application_id" FOREIGN KEY ("application_id") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "deployment_package_applications_deployment_package_id" FOREIGN KEY ("deployment_package_id") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_package_icon" table
ALTER TABLE "deployment_package_icon" ADD CONSTRAINT "deployment_package_icon_artifact_id" FOREIGN KEY ("artifact_id") REFERENCES "artifacts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "deployment_package_icon_deployment_package_id" FOREIGN KEY ("deployment_package_id") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_package_thumbnail" table
ALTER TABLE "deployment_package_thumbnail" ADD CONSTRAINT "deployment_package_thumbnail_artifact_id" FOREIGN KEY ("artifact_id") REFERENCES "artifacts" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "deployment_package_thumbnail_deployment_package_id" FOREIGN KEY ("deployment_package_id") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "deployment_profile_profiles" table
ALTER TABLE "deployment_profile_profiles" ADD CONSTRAINT "deployment_profile_profiles_deployment_profile_id" FOREIGN KEY ("deployment_profile_id") REFERENCES "deployment_profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD CONSTRAINT "deployment_profile_profiles_profile_id" FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
