-- Create "ignored_resources" table
CREATE TABLE "ignored_resources" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "kind" character varying NOT NULL, "application_ignored_resources" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "ignored_resources_applications_ignored_resources" FOREIGN KEY ("application_ignored_resources") REFERENCES "applications" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "ignoredresource_name_kind_application_ignored_resources" to table: "ignored_resources"
CREATE UNIQUE INDEX "ignoredresource_name_kind_application_ignored_resources" ON "ignored_resources" ("name", "kind", "application_ignored_resources");
