-- Modify "profiles" table
ALTER TABLE "profiles" ADD COLUMN "parameter_template_profiles" bigint NULL;
-- Create "parameter_templates" table
CREATE TABLE "parameter_templates" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "display_name" character varying NULL, "display_name_lc" character varying NULL, "default" character varying NULL, "type" character varying NULL, "validator" character varying NULL, "suggested_values" jsonb NULL, "profile_parameter_templates" bigint NOT NULL, PRIMARY KEY ("id"));
-- Modify "profiles" table
ALTER TABLE "profiles" ADD CONSTRAINT "profiles_parameter_templates_profiles" FOREIGN KEY ("parameter_template_profiles") REFERENCES "parameter_templates" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- Modify "parameter_templates" table
ALTER TABLE "parameter_templates" ADD CONSTRAINT "parameter_templates_profiles_parameter_templates" FOREIGN KEY ("profile_parameter_templates") REFERENCES "profiles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
