-- Modify "deployment_packages" table
ALTER TABLE "deployment_packages" ADD COLUMN "allows_multiple_deployments" boolean NULL;
-- Create "deployment_requirements" table
CREATE TABLE "deployment_requirements" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "deployment_requirement_deployment_package_fk" bigint NOT NULL, "profile_deployment_requirements" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "deployment_requirements_deploy_f4be18691c216d42715da2d256443f05" FOREIGN KEY ("deployment_requirement_deployment_package_fk") REFERENCES "deployment_packages" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "deployment_requirements_profiles_deployment_requirements" FOREIGN KEY ("profile_deployment_requirements") REFERENCES "profiles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Modify "deployment_profiles" table
ALTER TABLE "deployment_profiles" ADD COLUMN "deployment_requirement_deployment_profile_fk" bigint NULL, ADD CONSTRAINT "deployment_profiles_deployment_fce10a7872a343d005bd76050d0329a0" FOREIGN KEY ("deployment_requirement_deployment_profile_fk") REFERENCES "deployment_requirements" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
