// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

package northbound

/* The Catalog Service supports import of helm charts from OCI registries.
 *
 * The OCI helm chart is fetched from the registry, and then a deployment package,
 * application, and registry are generated from the chart.
 */

import (
	"context"

	"github.com/open-edge-platform/app-orch-catalog/internal/dp"
	"github.com/open-edge-platform/app-orch-catalog/internal/helm"
	"github.com/open-edge-platform/app-orch-catalog/internal/northbound/nberrors"
	"github.com/open-edge-platform/app-orch-catalog/internal/shared/verboseerror"
	catalogv3 "github.com/open-edge-platform/app-orch-catalog/pkg/api/catalog/v3"
)

func verboseNBError(err error) error {
	opts := []nberrors.Option{nberrors.WithMessage("%s", err.Error()),
		nberrors.WithError(err)}
	verboseErrMsg := verboseerror.VerboseErrorAsString(err)
	if verboseErrMsg != "" {
		opts = append(opts, nberrors.WithDetails(verboseErrMsg))
	}
	return nberrors.NewInvalidArgument(opts...)
}

// Import allows a helm chart to be imported from an OCI registry
func (g *Server) Import(ctx context.Context, req *catalogv3.ImportRequest) (*catalogv3.ImportResponse, error) {
	projectUUID, err := GetActiveProjectID(ctx)
	if err != nil {
		return nil, err
	}

	if req == nil || req.Url == "" {
		return nil, nberrors.NewInvalidArgument(
			nberrors.WithMessage("incomplete request"))
	}

	if err = g.authCheckAllowed(ctx, req); err != nil {
		return nil, err
	}

	helm, err := helm.FetchHelmChartOCI(req.Url, req.Username, req.AuthToken)
	if err != nil {
		return nil, verboseNBError(err)
	}

	if req.GenerateDefaultValues && req.ChartValues != "" {
		return nil, nberrors.NewInvalidArgument(
			nberrors.WithMessage("Cannot specify both GenerateDefaultValues and Values in the request"))
	}

	var values string
	if req.GenerateDefaultValues {
		values, err = dp.GetValuesFromChart(helm)
		if err != nil {
			return nil, verboseNBError(err)

		}
	} else {
		values = req.ChartValues
	}

	_, pkg, app, reg, err := dp.GenerateDeploymentPackageResources(helm, values, req.Namespace, req.IncludeAuth)
	if err != nil {
		return nil, verboseNBError(err)
	}

	if req.GenerateDefaultParameters {
		pts, err := dp.GenerateDefaultParameters(values)
		if err != nil {
			return nil, verboseNBError(err)
		}
		app.Profiles[0].ParameterTemplates = pts // all autogenerated apps contain exactly one profile
	}

	tx, err := g.startTransaction(ctx)
	if err != nil {
		return nil, nberrors.NewDBError(nberrors.WithError(err))
	}

	allowOverwriteRegistry := !g.IsSystemRegistry(reg.Name)
	registryEvents := &RegistryEvents{}
	err = g.createOrUpdateRegistry(ctx, tx, projectUUID, reg, registryEvents, allowOverwriteRegistry)
	if err != nil {
		g.rollbackTransaction(tx)
		return nil, nberrors.NewDBError(nberrors.WithError(err))
	}

	appEvents := &ApplicationEvents{}
	err = g.createOrUpdateApplication(ctx, tx, projectUUID, app, appEvents)
	if err != nil {
		g.rollbackTransaction(tx)
		return nil, nberrors.NewDBError(nberrors.WithError(err))
	}

	dpEvents := &DeploymentPackageEvents{}
	err = g.createOrUpdateDeploymentPackage(ctx, tx, projectUUID, pkg, dpEvents)
	if err != nil {
		g.rollbackTransaction(tx)
		return nil, nberrors.NewDBError(nberrors.WithError(err))
	}

	err = g.commitTransaction(tx)
	if err != nil {
		return nil, nberrors.NewDBError(nberrors.WithError(err))
	}

	logActivity(ctx, "created", "registry", projectUUID, reg.Name)
	logActivity(ctx, "created", "application", projectUUID, app.Name, app.Version)
	logActivity(ctx, "created", "deployment-package", projectUUID, pkg.Name, pkg.Version)

	registryEvents.sendToAll(g.listeners)
	appEvents.sendToAll(g.listeners)
	dpEvents.sendToAll(g.listeners)

	resp := &catalogv3.ImportResponse{}
	return resp, nil
}
