// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
//
// SPDX-License-Identifier: Apache-2.0

package northbound

/* The Catalog Service supports Uploads via the Upload endpoint.
 *
 * An upload consists of a set of files. These may either be individual YAML files or
 * they may be tarballs that contain individual YAML files. If a tarball is provided, then
 * it will be extracted and the individual YAML files will be processed.
 *
 * Each tarball is loaded independently, and the tarballs are loaded independently of raw
 * yaml files that may be present.
 */

import (
	"context"

	"github.com/open-edge-platform/app-orch-catalog/internal/ent/generated"
	"github.com/open-edge-platform/app-orch-catalog/internal/ent/generated/application"
	"github.com/open-edge-platform/app-orch-catalog/internal/ent/generated/deploymentpackage"
	"github.com/open-edge-platform/app-orch-catalog/internal/ent/generated/registry"
	"github.com/open-edge-platform/app-orch-catalog/internal/northbound/nberrors"
	catalogv3 "github.com/open-edge-platform/app-orch-catalog/pkg/api/catalog/v3"
)

// registryIsEquivalent checks whether an Registry Protobuf object is functionally the same as a Registry ENT object
func (g *Server) registryIsEquivalent(ctx context.Context, reg1 *catalogv3.Registry, reg2 *generated.Registry, projectUUID string) (bool, error) {
	// These ones are easy to check because they are directly represented in the ENT schema
	if reg1.Name != reg2.Name || reg1.DisplayName != reg2.DisplayName || reg1.Type != reg2.Type {
		return false, nil
	}

	// Description has no impact on functionality and is not checked.

	// AuthToken, CaCerts, ApiType, RootURL, InventoryURL, Username, and Authtoken are stored in Vault
	var encodedSecretData string
	if UseSecretService {
		secretService, err := SecretServiceFactory(ctx)
		if err != nil {
			return false, nberrors.NewVaultError(nberrors.WithError(err))
		}
		defer secretService.Logout(ctx)

		registryKey := MakeSecretPath(projectUUID, reg2.Name)

		// Fetch the stored secret
		encodedSecretData, err = secretService.ReadSecret(ctx, registryKey)
		if err != nil {
			return false, nberrors.NewVaultError(nberrors.WithError(err))
		}
	} else {
		// If secrets service is not enabled, then everything is packed into the AuthToken field of
		// the ENT object.
		encodedSecretData = reg2.AuthToken
	}

	rsd := registrySecretData{}
	err := Base64Factory().DecodeBase64(&rsd, encodedSecretData)
	if err != nil {
		return false, nberrors.NewVaultError(nberrors.WithError(err))
	}

	return reg1.AuthToken == rsd.AuthToken && reg1.Cacerts == rsd.Cacerts && reg1.ApiType == reg2.APIType && reg1.RootUrl == rsd.RootURL && reg1.InventoryUrl == rsd.InventoryURL && reg1.Username == rsd.Username, nil
}

func (g *Server) createOrUpdateRegistry(ctx context.Context, tx *generated.Tx, projectUUID string, reg *catalogv3.Registry, registryEvents *RegistryEvents, allowOverwrite bool) error {
	existingReg, err := tx.Registry.Query().Where(registry.ProjectUUID(projectUUID), registry.Name(reg.Name)).First(ctx)
	if err != nil {
		_, err = g.createRegistry(ctx, tx, projectUUID, reg, registryEvents)
	} else {
		if !allowOverwrite {
			// Registries are often shared between multiple applications, and there are significant negative
			// consequences to overwriting an existing registry, especially if it is oci-harbor-helm or
			// oci-harbor-docker, which is generated by the system. `allowOverwrite` can be used to refuse
			// modifying registries that already exist.
			isEquivalent, err := g.registryIsEquivalent(ctx, reg, existingReg, projectUUID)
			if err != nil {
				return err
			}
			if !isEquivalent {
				return nberrors.NewAlreadyExists(
					nberrors.WithResourceType(nberrors.RegistryType),
					nberrors.WithResourceName(reg.Name),
					nberrors.WithMessage("registry with name '%s' already exists", reg.Name))
			}
			// The registry is equivalent, but maybe a field that does not impact functionality, such as
			// Description, has changed. Proceed to update the registry to pick up any such changes.
		}

		err = g.updateRegistry(ctx, tx, projectUUID, reg, registryEvents)
	}
	return err
}

func (g *Server) createOrUpdateApplication(ctx context.Context, tx *generated.Tx, projectUUID string, app *catalogv3.Application, appEvents *ApplicationEvents) error {
	_, err := tx.Application.Query().Where(application.ProjectUUID(projectUUID), application.Name(app.Name), application.Version(app.Version)).First(ctx)
	if err != nil {
		_, err = g.createApplication(ctx, tx, projectUUID, app, appEvents)
	} else {
		err = g.updateApplication(ctx, tx, projectUUID, app, appEvents)
	}
	return err
}

func (g *Server) createOrUpdateDeploymentPackage(ctx context.Context, tx *generated.Tx, projectUUID string, pkg *catalogv3.DeploymentPackage, dpEvents *DeploymentPackageEvents) error {
	_, err := tx.DeploymentPackage.Query().Where(deploymentpackage.ProjectUUID(projectUUID),
		deploymentpackage.Name(pkg.Name), deploymentpackage.Version(pkg.Version)).First(ctx)
	if err != nil {
		_, err = g.createDeploymentPackage(ctx, tx, projectUUID, pkg, dpEvents)
	} else {
		err = g.updateDeploymentPackage(ctx, tx, projectUUID, pkg, dpEvents)
	}
	return err
}
