# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
fullnameOverride: tutorial-server
tutorialServer:
  greeting: "Deployed by Application Orchestration (alternate)"
  initialCount: 5
image:
  #  Will update with your CLUSTER_FQDN and your ORG and PROJECT names
  repository: %ImageRegistryURL%/tutorial-server-image
imagePullSecrets:
  - name: "%GeneratedDockerCredential%"
