# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

---
fullnameOverride: tutorial-web-ui
image:
  #  Please update with your CLUSTER_FQDN and your ORG and PROJECT names
  repository: registry-oci.<CLUSTER_FQDN>/catalog-apps-<ORG>-<PROJECT>/tutorial-web-ui-image
imagePullSecrets:
  - name: "%GeneratedDockerCredential%"
service:
  annotations:
    service-proxy.app.orchestrator.io/ports: "80"
