# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
---
global:
  registry_address: ghcr.io
  docker_namespace: open-edge-platform/geti
  debian:
    name: os-shell:12-debian-12-r47

auth-proxy:
  certificate:
    issuerRef:
      name: edge-node-cluster-issuer
