# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
  # SPDX-License-Identifier: Apache-2.0
---
{{- if .Values.modifyResource.secret}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "httpbin.fullname" . }}-test-secret
  annotations:
    test-annotation: "true"
type: Opaque
data:
  some-key: {{ printf "original value" | b64enc }}
{{- end }}
