# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "application-catalog.fullname" . }}
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
data:
  logging.yaml: |-
{{ toYaml .Values.logging | indent 4 }}
---
{{ if .Values.openpolicyagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application-catalog.fullname" . }}-opa-rego
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/openpolicyagent/*.rego").AsConfig | indent 2 }}
{{- end}}