# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-catalog.fullname" . }}-rest-proxy
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.restProxy.type }}
  ports:
    - port: {{ .Values.service.restProxy.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "application-catalog.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-catalog.fullname" . }}-grpc-server
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.grpcServer.type }}
  ports:
    - port: {{ .Values.service.grpcServer.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "application-catalog.selectorLabels" . | nindent 4 }}
---
{{- if .Values.openpolicyagent.enabled -}}
{{- if .Values.service.opa.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "application-catalog.fullname" . }}-opa
  labels:
    {{- include "application-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.opa.type }}
  ports:
    - port: {{ .Values.service.opa.port }}
      protocol: TCP
      name: http-opa
  selector:
    {{- include "application-catalog.selectorLabels" . | nindent 4 }}
{{- end}}
{{- end}}
