apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tutorial-web-ui.fullname" . }}
  labels:
    {{- include "tutorial-web-ui.labels" . | nindent 4 }}
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /api/ {
            proxy_pass {{.Values.tutorialServer.proto}}://{{.Values.tutorialServer.host}}:{{.Values.tutorialServer.port}}/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_connect_timeout       {{ .Values.tutorialServer.streamTimeout }};
            proxy_send_timeout          {{ .Values.tutorialServer.streamTimeout }};
            proxy_read_timeout          {{ .Values.tutorialServer.streamTimeout }};
            send_timeout                {{ .Values.tutorialServer.streamTimeout }};
        }
    }
