apiVersion: v1
kind: Service
metadata:
  name: {{ include "tutorial-web-ui.fullname" . }}
  labels:
    {{- include "tutorial-web-ui.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations: {{- .Values.service.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tutorial-web-ui.selectorLabels" . | nindent 4 }}
