---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Component Tests
on:
  pull_request:
    types: [labeled]
  schedule:
    - cron: "0 0 * * *" # Run every day at midnight
  workflow_dispatch:  # Run on manual trigger
    inputs:
      run-component-tests:
        description: 'Run component tests'
        required: true
        type: boolean
        default: false
      emf-branch:
        description: 'The branch, tag or SHA to checkout EMF'
        required: true
        type: string
        default: '53e430f45faaee7671fa3c25f6acc3945aba2065'

permissions:
  contents: read

jobs:
  component-tests:
    name: Deploy OnPrem Orchestrator and Run Component Tests
    if: |
      ${{ inputs.run-component-tests || github.event_name == 'schedule' || github.event.label.name == 'run-component-tests' }}
    runs-on: ubuntu-24.04-16core-64GB # ubuntu-24.04-4core-16GB ubuntu-22.04-32core-128GB & ubuntu-24.04-16core-64GB
    timeout-minutes: 60
    env:
      ORCH_DEFAULT_PASSWORD: ${{ secrets.ORCH_DEFAULT_PASSWORD }}
      CODER_DIR: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1
        with:
            repository: open-edge-platform/edge-manageability-framework
            token: ${{ secrets.SYS_ORCH_GITHUB }}
            ref: feature/deploy-onprem-gha
            persist-credentials: false
            path: emf

      #- name: Deploy On Prem Orchestrator
      #  uses: ./emf/.github/actions/deploy_on_prem  # yamllint disable-line rule:line-length
      #  with:
      #    token: ${{ secrets.SYS_ORCH_GITHUB }}
      #    orch_version: ${{ inputs.emf-branch || 'main' }}
      #    docker_username: ${{ secrets.SYS_DOCKERHUB_USERNAME }}
      #    docker_password: ${{ secrets.SYS_DOCKERHUB_RO }}

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Checkout app-orch-catalog repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          repository: open-edge-platform/app-orch-catalog
          path: app-orch-catalog
          token: ${{ secrets.SYS_ORCH_GITHUB }}
          persist-credentials: false

      # ls the whole workspace
      - name: List workspace
        working-directory: emf
        run: ls -la

      - name: Get current git hash of the app-orch-catalog PR
        id: get-git-hash-catalog
        working-directory: app-orch-catalog
        env:
          GIT_HASH_CHARTS: ${{ github.event.pull_request.head.sha }}
        run: echo "GIT_HASH_CHARTS=$GIT_HASH_CHARTS" >> "$GITHUB_ENV"

      - name: Get current git hash of the edge-manageability-framework PR
        id: get-git-hash-deploy
        working-directory: emf
        run: echo "GIT_HASH_DEPLOY=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: Setup asdf and install dependencies
        id: install-deps
        uses: open-edge-platform/orch-utils/.github/actions/setup-asdf@main  # zizmor: ignore[unpinned-uses]

      - name: test mage
        working-directory: emf
        run: mage -version
      - name: Setup users and project/org
        shell: bash
        working-directory: emf
        run: |
          mage tenantUtils:createDefaultMtSetup
          echo "Orch org/project/users created!"
          echo "Project uID:"
          kubectl get projects.project -o json | jq -r ".items[0].status.projectStatus.uID"

      - name: Build binaries
        working-directory: app-orch-catalog
        run: |
          make build

      - name: Redeploy and Rebuild app-orch-catalog
        working-directory: app-orch-catalog
        run: |
          make coder-redeploy
          make coder-rebuild 

      - name: Describe app-orch-catalog
        run: kubectl describe deployments.app -n orch-app app-orch-catalog

      - name: Wait for app-orch-catalog pod to be Running
        run: |
          while true; do
            POD_NAME=$(kubectl get pods -n orch-app -l app.kubernetes.io/instance=app-orch-catalog -o jsonpath='{.items[0].metadata.name}')
            POD_STATUS=$(kubectl get pod $POD_NAME -n orch-app -o jsonpath='{.status.phase}')
            if [ "$POD_STATUS" == "Running" ]; then
              echo "Pod $POD_NAME is in Running state."
              break
            else
              echo "Pod $POD_NAME is not in Running state. Current state: $POD_STATUS"
              echo "Waiting for 10 seconds before checking again..."
              sleep 10
            fi
          done  

      - name: Run Catalog Component Tests
        working-directory: app-orch-catalog/test
        env:
          PATH: ${{ env.PATH }}:${{ env.GOPATH }}/bin
        run: |
          make component-tests
          echo "Component tests done!"
      - name: Report
        uses: becheran/go-testreport@main
        with:
          input: app-orch-catalog/test/test-report.json
          output: app-orch-catalog/test/${{ github.event_name }}-${{ github.event.number }}-test-report.html
          template: app-orch-catalog/test/template.html

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        with:
          name: test-report
          path: app-orch-catalog/test/${{ github.event_name }}-${{ github.event.number }}-test-report.html
