---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Go Fuzzing Tests

on:
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:
    inputs:
      run_catalog:
        description: 'Run Catalog fuzzing tests'
        required: false
        type: boolean
        default: true
      fuzz_seconds_catalog:
        description: 'Duration per test case in secs. Total duration is secs x # of test cases'
        required: false
        type: number
        default: 60
  # Scheduled workflows will only run on the default branch. Input values from workflow_dispatch will be null when schedule event is triggered
  schedule:
    - cron: "0 0 * * 6"   # every week, at 00:00 on Saturday

jobs:
  go-fuzz-catalog:
    name: Catalog Go Fuzzing Tests
    runs-on: ${{ github.repository_owner == 'intel' && 'intel-ubuntu-latest' || 'ubuntu-latest' }}
    steps:
    - name: Checkout app-orch-deployment repository
      uses: actions/checkout@v4
      with:
        repository: open-edge-platform/app-orch-deployment
        path: ao
        token: ${{ secrets.SYS_ORCH_GITHUB }}
    - name: ls
      shell: bash
      run: |
        echo "Current working directory:"
        pwd
        echo
        echo "ls"
        ls
        echo
        echo "ls ao"
        ls ao
        echo
    - name: Catalog Go Fuzzing Tests
      uses: ./ao/app-orch-deployment/.github/workflows/common-go-fuzz.yml
      with:
        # Declare 4800 secs duration since schedule event will not pick up input values from workflow_dispatch
        fuzz_seconds: ${{ inputs.fuzz_seconds_catalog || 2 }}
        test_data_dir: ./internal/northbound/testdata/fuzz
